<?php

namespace protecno\adminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * autoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class autoRepository extends EntityRepository
{
	public function findSlider() {
	    $em = $this->getEntityManager();
        $dql = "select s,g
            from adminBundle:galeria g
            join g.imagenes s
            ";//group by p.id
//echo $dql.$carrito;
        $query = $em->createQuery($dql);
        $articulos = $query->getArrayResult();
       // print_r($articulos);
        return $articulos;
     }

    public function findMaxMin() {
        $em = $this->getEntityManager();
        $dql = "SELECT MAX(a.precio)AS alto,MIN(a.precio) AS bajo FROM adminBundle:auto a";//group by p.id
//echo $dql.$carrito;
        $query = $em->createQuery($dql);
        $articulos = $query->getArrayResult();
       // print_r($articulos);
        return $articulos[0];
     }

    public function findOfertas($limit) {
	    $em = $this->getEntityManager();
        $dql = "select s,a,m
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            where a.rebaja=true
            order by a.fCreacion desc ";//group by p.id

        $query = $em->createQuery($dql)
        		->setMaxResults($limit);
       // $query->setParameter('usuario', $usuario);
        $productos = $query->getArrayResult();
        //print_r($productos);
        return $productos;
     }
    public function findTop($limit) {
	    $em = $this->getEntityManager();
        $dql = "select s,a,m
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            order by a.visitas desc ";//group by p.id

        $query = $em->createQuery($dql)
        		->setMaxResults($limit);
       // $query->setParameter('usuario', $usuario);
        $productos = $query->getArrayResult();
        //print_r($productos);
        return $productos;
     }

    public function findProducto($id) {
	    $em = $this->getEntityManager();
        $dql = "select s,a,m,ma
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            join m.marca ma
            where a.id=:id ";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
        //echo '<pre>';print_r($producto[0]);echo '</pre>';
        return $producto[0];
     }

    public function findProductoBymodelo($id,$auto,$limit) {
	    $em = $this->getEntityManager();
        $dql = "select s,a,m
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            where m.id=:id and a.id <> :auto ";//group by p.id

        $query = $em->createQuery($dql)
        			->setMaxResults($limit);
        $query->setParameter('id', $id);
        $query->setParameter('auto', $auto);
        $producto = $query->getArrayResult();
        //print_r($productos);
        return $producto;
     }

    public function findByCategoria($id,$limit) {
        $em = $this->getEntityManager();
        $dql = "select s,a,m
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            join a.categoria c
            where c.id=:id order by a.fCreacion desc";//group by p.id

        $query = $em->createQuery($dql)
                    ->setMaxResults($limit);
        $query->setParameter('id', $id);
       // $query->setParameter('auto', $auto);
        $producto = $query->getArrayResult();
        //print_r($productos);
        return $producto;
     }
     public function findByMarca($id,$limit) {
        $em = $this->getEntityManager();
        $dql = "select s,a,m,ma
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            join m.marca ma
            where ma.id=:id order by a.fCreacion desc";//group by p.id

        $query = $em->createQuery($dql)
                    ->setMaxResults($limit);
        $query->setParameter('id', $id);
       // $query->setParameter('auto', $auto);
        $producto = $query->getArrayResult();
        //print_r($productos);
        return $producto;
     }

     public function findByRango($inicio,$fin) {
        $em = $this->getEntityManager();
        $dql = "select s,a,m,ma
            from adminBundle:auto a
            join a.modelo m
            join a.imagenes s
            join m.marca ma
            where a.precio>:inicio and a.precio < :fin order by a.fCreacion desc";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('inicio', $inicio);
        $query->setParameter('fin', $fin);
        $producto = $query->getArrayResult();
        //print_r($productos);
        return $producto;
     }

      public function findByEtiqueta($limit) {
        //echo 'hola';
        $em = $this->getEntityManager();
        $dql = "select d,e,i
            from adminBundle:descargas d
            join d.etiqueta e
            join d.imagenes i
            order by d.id desc";//group by p.id

        $query = $em->createQuery($dql)
                    ->setMaxResults($limit);
       // $query->setParameter('id', $id);
       // $query->setParameter('auto', $auto);
          //          echo $dql;
        $producto = $query->getArrayResult();
        //print_r($producto);
        return $producto;
     }

    public function findTips($limit) {
        //echo 'hola';
        $em = $this->getEntityManager();
        $dql = "select t,i
            from adminBundle:tips t
            join t.imagenes i
            order by t.id desc";//group by p.id

        $query = $em->createQuery($dql)
                    ->setMaxResults($limit);
       // $query->setParameter('id', $id);
       // $query->setParameter('auto', $auto);
          //          echo $dql;
        $producto = $query->getArrayResult();
        //print_r($producto);
        return $producto;
     }
}
