<?php

namespace protecno\adminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * autoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class autoRepository extends EntityRepository
{
}
