services:
    sonata.admin.post:
        class: protecno\adminBundle\admin\marcaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Marcas" }
        arguments:
            - ~
            - protecno\adminBundle\Entity\marca
            - ~
        calls:
            - [ setTranslationDomain, [adminBundle]]
    sonata.admin.categoria:
        class: protecno\adminBundle\admin\categoriaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categorias" }
        arguments:
            - ~
            - protecno\adminBundle\Entity\categorias
            - ~
        calls:
            - [ setTranslationDomain, [adminBundle]]
    sonata.admin.categoria:
        class: protecno\adminBundle\admin\autoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Vehiculos" }
        arguments:
            - ~
            - protecno\adminBundle\Entity\auto
            - ~
        calls:
            - [ setTranslationDomain, [adminBundle]]