protecno\adminBundle\Entity\auto:
    type: entity
    table: null
    repositoryClass: protecno\adminBundle\Entity\autoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        modelo:
            type: string
            length: '50'
        anio:
            type: string
            length: '4'
        codigo:
            type: string
            length: '20'
        motor:
            type: string
            length: '20'
        km:
            type: string
            length: '12'
        interior:
            type: string
            length: '50'
        exterior:
            type: string
            length: '50'
        puertas:
            type: integer
        llaves:
            type: string
            length: '4'
        tenencia:
            type: string
            length: '20'
        verificacion:
            type: string
            length: '20'
        refacturacion:
            type: string
            length: '4'
        precio:
            type: string
            length: '20'
        gastosReparacion:
            type: string
            length: '20'
        observaciones:
            type: text
    manyToOne:
        parent:
            targetEntity: protecno\adminBundle\Entity\marca
            inversedBy: auto
    manyToMany:
        categoria:
          targetEntity: protecno\adminBundle\Entity\categorias
          joinTable:
            name: auto_categoria
            joinColumns:
              auto_id:
                referencedColumnName: id
            inverseJoinColumns:
              categoria_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
