protecno\adminBundle\Entity\pagina:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '50'
        orden:
            type: integer
        contenido:
            type: text
    lifecycleCallbacks: {  }
