protecno\adminBundle\Entity\slider:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: '120'
            nullable:     true
        subtitulo:
            type: string
            length: '120'
            nullable:     true
        orden:
            type: integer
            nullable:     true
        path:
            type: string
            length: '120'
            nullable:     true
        imagen:
            type: string
            length: '120'
            nullable:     true
        updated:       
            type:         datetime
            nullable:     true
    lifecycleCallbacks: 
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]
